name: Poke
version: '${project.version}'
main: com.consolex.poke.Poke
api-version: 1.18
authors: [ ConsoleX ]
description: A plugin that allows players to @ other players in chat. 
commands:
  poke:
    desciption: Opens sound preferences
    usage: /<command>
  pokecolor:
    description: Changes poke colors
    usage: /<command> color